In [1]:
a = 12
b = 30
print(a + b)

42


In [4]:
Naimat = 'My wife'
print(Naimat)

My wife


In [5]:
txt = 'Hallo my friends'
print(txt)

Hallo my friends


In [6]:
txt1 = ' 3 months ago i was in Dubai'
print(txt1)

 3 months ago i was in Dubai


In [ ]:
first_name = input('What is your first name'

In [1]:
## print function 
print('the sky is blue')

the sky is blue


In [ ]:
# exemple

name = 'chritiana'
age = 30
height

In [4]:
## INDEXING AND SLICING

#SLICING - slice() it returns a slice object that is used to slice any sequence(strings, tople, or a range or list)

wux = 'python programming class'

# i need to get a slice object, to get a slice object for 'python'

slice_wux = slice(6)
print(wux[slice_wux])



python


In [6]:


# slice (start, end, step) # if the step is not indicated, it means  by default is 1

wux = 'python programming class'

# to get slice object for 'programming'

slice_wux2 = slice(7,18)
print(wux[slice_wux2])


programming


In [7]:
# Breadknife # (start : end: step) [start : end:]


r = 'football'
print(r[3])

t


In [8]:
print(r[4:8])

ball


In [9]:
print(r[4:])

ball


In [ ]:
print(r)

In [16]:
#breadknife 

#extract programming from variable wux

print(wux[7:18])

programming


In [19]:
# Dictionary - it is used to store data values in key ordered parts - abbreviated word is 'dict' 
'''''' it can be writen using curly bracket, and it has keys and values. it can omly be changed

ordered but not duplicated ''

x_dict = {'car_brand': 'ford', 'car_model': 'mustang', 'year': 2020}
print(x_dict)

SyntaxError: invalid syntax (2308009779.py, line 2)

In [20]:
print(x_dict )

NameError: name 'x_dict' is not defined

In [ ]:
x_dict = {'car_brand': 'ford', 'car_model': 'mustang', 'year': 2020}
print(x_dict)

In [1]:
a = 12
b = 30
print(f'add {a} and b {b}' is (a + b)', )

SyntaxError: unterminated string literal (detected at line 3) (3999384790.py, line 3)

In [ ]:
## loop - 
- it is used to itrate over a sequence

In [3]:
list_num = ['lion', 'Car', 'sheep', 'Ram', 'Elephant']
print(list_num)

['lion', 'Car', 'sheep', 'Ram', 'Elephant']


In [4]:
type(list_num)

list

In [2]:
list_num1 = ['lion', 'Car', 'sheep', 'Ram', 'Elephant']

def short(x):
    return len(x) > 3
names_short =filter(short, list_num1)
print(list(names_short))

['lion', 'sheep', 'Elephant']


In [12]:
name = 'Faruk'
age = 38
height = 1.5

print(f'My name is {name}, and i am {age} my height is {height}')

My name is Faruk, and i am 38 my height is 1.5


In [3]:
#Numpy
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr)

[1 2 3 4 5 6 7 8]


In [ ]:
### shape, attribute and method 
-- shapes gives the number of column and rows and an array or dataframe. (R,C)


-- Attribute - it gives the metadata information about an object, and no bracket. eg .shapes .dtype .column .index, .values etc


-- Method - is a function associated with object, and it has bracket eg:  .append(), .index(), .capitalize(), .replace(), etc 
    
    
    

In [5]:
type(arr)

numpy.ndarray

In [10]:
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [11]:
arr1.shape

(2, 3)

In [12]:
arr1.size

6

In [18]:
#linspace() - it is an inbuilt function in numpy that creats sequences of evenly spaced arrays array, i.e Row*Column

np.linspace(0, 100, 5)



array([  0.,  25.,  50.,  75., 100.])

In [19]:
## Random- we can randomly generate numbers using numpy

random works with .rand(), .randn(), .randint() to generate numbers. 

- rand() is an inbuit method that returns random float numbers between 0 and 1

- randn() it is an inbuilt method that create an array of specified shape and fills it witha random values as per standard normal distribution


- randint() it is an inbuilt method tht  returns an interger number selected element from the specified range. 


SyntaxError: invalid syntax (1145859918.py, line 3)

In [20]:
np.random.rand(10)


array([0.49625898, 0.72239345, 0.06090943, 0.31399541, 0.09227269,
       0.85654612, 0.20870457, 0.73289688, 0.605791  , 0.25254251])

In [21]:
np.random.randn(10)

array([-0.04939766, -0.71071683,  1.12983794, -0.37482129, -0.55544354,
        2.31009551,  0.85483713,  1.29229697,  0.6711816 , -1.95395813])

In [24]:
np.random.randint(2, 10)

6

In [ ]:
# indexing in numpy

In [25]:
print(arr1)

[[1 2 3]
 [4 5 6]]


In [26]:
# indexing and slicing

arr1[0] # focusing on the row

array([1, 2, 3])

In [27]:
arr1[1]

array([4, 5, 6])

In [46]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [3,11,12]])
print(arr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 3 11 12]]


In [31]:
type(arr2)

numpy.ndarray

In [43]:
arr2.shape

(4, 3)

In [33]:
arr2.size

9

In [34]:
# arr2[start: end]

arr2[:,1] # focus on the column


array([2, 5, 8])

In [36]:
arr2[1:, ]

array([[4, 5, 6],
       [7, 8, 9]])

In [37]:
arr2[2:, 1]

array([8])

In [38]:
#Descriptive statistics sometimes called summary statistics - measure of centeral tendency (mean, median and mode)

print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
np.mean(arr2)

5.333333333333333

In [47]:
np.median(arr2)

5.5

In [51]:
from scipy import stats

arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 1, 1, 3, 3, 3, 4, 4, 4, 4,]
mode = stats.mode(arr)
print(mode)

C:\Users\FARUK MANDIBO\AppData\Local\Temp\ipykernel_7600\3447583276.py:4: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode = stats.mode(arr)


ModeResult(mode=array([4]), count=array([5]))


In [ ]:
### Pandas

** Series ====> 1 dimention

*** Dataframe =====> 2 dimension 



In [52]:
import pandas as pd

In [56]:
ages =[1, 11, 12, 23, 13, 14, 2, 4]

age_series = pd.Series(ages)
print(age_series)

0     1
1    11
2    12
3    23
4    13
5    14
6     2
7     4
dtype: int64


In [57]:
type(age_series)

pandas.core.series.Series

In [58]:
# Indexing

age_series[4]

13

In [59]:
age_series.values

array([ 1, 11, 12, 23, 13, 14,  2,  4], dtype=int64)

In [60]:
age_series.index

RangeIndex(start=0, stop=8, step=1)

In [62]:
#create a series from the dictionary \


car ={'ford': 200, 'Toyota': 150, 'Lexus': 300, 'Jeep': 400}
print(car)

{'ford': 200, 'Toyota': 150, 'Lexus': 300, 'Jeep': 400}


In [63]:
type(car)

dict

In [64]:
car_brand = pd.Series(car)
print(car_brand)

ford      200
Toyota    150
Lexus     300
Jeep      400
dtype: int64


In [66]:
car_brand.values

array([200, 150, 300, 400], dtype=int64)

In [67]:
# we can perform aggregate function on series 

# mean(), max(), min(), count(), sum() 

total_car = car_brand.sum()
print(total_car)

1050


In [68]:
avg_car = car_brand.mean()
print(avg_car)

262.5


In [69]:
max_car = car_brand.max()
print(max_car)

400


In [70]:
min_car = car_brand.min()
print(min_car)

150


In [71]:
count_car = car_brand.count()
print(count_car)

4


In [73]:
# .describe() is an inbuit method used on pandas pn to either Series or Dataframe to get summmary statistics

car_brand.describe().astype(int)

count      4
mean     262
std      110
min      150
25%      187
50%      250
75%      325
max      400
dtype: int32

In [74]:
#Dataframe - is two dimensions (rows and column)

y_dict = {'car_brand': ['ford', 'toyota', 'lexus','tesla'],
         'car_model': ['mustang', 'camry', 'rex340', 'spoty'],
         'Year': ['2020', '2005', '2006','2007']}
print(y_dict)

{'car_brand': ['ford', 'toyota', 'lexus', 'tesla'], 'car_model': ['mustang', 'camry', 'rex340', 'spoty'], 'Year': ['2020', '2005', '2006', '2007']}


In [75]:
type(y_dict)

dict

In [78]:
print(y_dict)

{'car_brand': ['ford', 'toyota', 'lexus', 'tesla'], 'car_model': ['mustang', 'camry', 'rex340', 'spoty'], 'Year': ['2020', '2005', '2006', '2007']}


In [82]:
# for best practices, Dataframe is written as this: df
df = pd.Dataframe()

AttributeError: module 'pandas' has no attribute 'Dataframe'

df_dict = pd.Dataframe(y_dict)
print(df_dict)

In [80]:
df_dict

NameError: name 'df_dict' is not defined

In [81]:
# we can use index for the Dataframe bu using .index

df.dict.index

NameError: name 'df' is not defined

In [ ]:


#pie chart

names = ['Faruk', 'Naimat', 'Ajimal', 'Bayo']
ages = (50, 14, 40, 60)

